# code: language=Ansible insertSpaces=true tabSize=2


- name: Lock Ansible user account password
  user:
    name: "{{ system_ansible_user_name }}"
    state: present
    password_lock: true
  tags: [never, setup]

- name: Unlock Ansible user account password
  user:
    name: "{{ system_ansible_user_name }}"
    state: present
    password_lock: false
  tags: [never, teardown, remove]
